-- SYS
GRANT  EXECUTE ON DBMS_OBFUSCATION_TOOLKIT TO scott; -- SCOTT에게 DBMS_OBFUSCATION_TOOLKIT 권한 부여
--
GRANT  EXECUTE ON DBMS_OBFUSCATION_TOOLKIT TO PUBLIC; -- DBMS_OBFUSCATION_TOOLKIT 모두에게 사용할 수 있도록 권한 부여